-- Add more common houseplant species

INSERT INTO species (key, name, water_days, light, humidity, fertilize_days, tip) VALUES
  ('aloe_vera', 'Aloe Vera', 14, 'bright_direct', 'low', 60, 'Allow soil to dry completely between waterings. The gel inside leaves soothes minor burns.'),
  ('boston_fern', 'Boston Fern', 3, 'medium_indirect', 'high', 30, 'Keep soil consistently moist and mist daily — ferns hate dry air.'),
  ('bird_of_paradise', 'Bird of Paradise', 7, 'bright_direct', 'medium', 30, 'Needs several hours of direct sun to bloom indoors. Wipe large leaves monthly.'),
  ('chinese_evergreen', 'Chinese Evergreen', 10, 'low_to_medium', 'medium', 45, 'Tolerates low light better than most plants. Avoid cold drafts.'),
  ('dracaena', 'Dracaena', 14, 'medium_to_bright_indirect', 'low', 60, 'Use filtered water — sensitive to fluoride which causes brown leaf tips.'),
  ('jade_plant', 'Jade Plant', 14, 'bright_direct', 'low', 60, 'A true succulent — let soil dry fully between waterings. Can live for decades.'),
  ('orchid', 'Orchid (Phalaenopsis)', 7, 'bright_indirect', 'medium', 30, 'Water by soaking roots for 15 min weekly, then drain completely. Rebloom by dropping night temps 10°F.'),
  ('african_violet', 'African Violet', 7, 'medium_indirect', 'medium', 14, 'Water from the bottom to avoid spotting leaves. Keeps blooming year-round with enough light.'),
  ('cactus', 'Cactus', 21, 'bright_direct', 'low', 90, 'Water sparingly in summer, almost not at all in winter. Needs lots of direct sunlight.'),
  ('string_of_pearls', 'String of Pearls', 14, 'bright_indirect', 'low', 60, 'Prone to root rot — always let soil dry out completely. Trailing vines look stunning in hanging pots.'),
  ('tradescantia', 'Tradescantia', 7, 'bright_indirect', 'medium', 30, 'Pinch back leggy stems to keep the plant bushy. Cuttings root easily in water.'),
  ('anthurium', 'Anthurium', 7, 'bright_indirect', 'high', 30, 'The waxy "flowers" are actually spathes. Mist regularly and keep away from cold drafts.'),
  ('begonia', 'Begonia', 7, 'medium_to_bright_indirect', 'medium', 30, 'Water at the base to prevent powdery mildew. Deadhead spent blooms to encourage new flowers.'),
  ('hoya', 'Hoya (Wax Plant)', 10, 'bright_indirect', 'medium', 45, 'Never remove the flower spurs — new blooms grow from the same spot each year.'),
  ('money_tree', 'Money Tree', 10, 'bright_indirect', 'medium', 30, 'Water thoroughly then let top few inches dry out. The braided trunk symbolizes good luck.'),
  ('prayer_plant', 'Prayer Plant', 5, 'medium_indirect', 'high', 30, 'Leaves fold up at night like hands in prayer. Use filtered water and keep humidity high.'),
  ('peperomia', 'Peperomia', 10, 'medium_to_bright_indirect', 'low', 45, 'Semi-succulent leaves store water — one of the easiest plants to keep. Tolerates neglect well.'),
  ('pilea', 'Pilea (Chinese Money Plant)', 7, 'bright_indirect', 'medium', 30, 'Rotate weekly for even growth. Produces lots of "pups" at the base that can be repotted.'),
  ('syngonium', 'Syngonium (Arrowhead Plant)', 7, 'medium_to_bright_indirect', 'medium', 30, 'Leaf shape changes dramatically as the plant matures. Trim to keep it bushy.'),
  ('parlor_palm', 'Parlor Palm', 10, 'low_to_medium', 'medium', 45, 'One of the best palms for low-light interiors. Avoid overwatering — let top inch dry out.'),
  ('schefflera', 'Schefflera (Umbrella Plant)', 10, 'bright_indirect', 'medium', 30, 'Prune regularly to control size. Toxic to pets.'),
  ('croton', 'Croton', 7, 'bright_direct', 'medium', 30, 'Needs maximum light to maintain its colorful foliage. Hates being moved — pick a good spot.'),
  ('dieffenbachia', 'Dieffenbachia', 7, 'medium_to_bright_indirect', 'medium', 30, 'Toxic if ingested — sap can cause mouth irritation. Wear gloves when pruning.'),
  ('english_ivy', 'English Ivy', 7, 'medium_to_bright_indirect', 'medium', 30, 'Keep cool and well-watered. Great for hanging baskets or training up a moss pole.'),
  ('haworthia', 'Haworthia', 14, 'bright_indirect', 'low', 60, 'Unlike most succulents, prefers indirect light. Perfect for bright windowsills without direct sun.'),
  ('echeveria', 'Echeveria', 14, 'bright_direct', 'low', 60, 'Water only when soil is bone dry. Avoid getting water in the rosette center to prevent rot.'),
  ('kalanchoe', 'Kalanchoe', 10, 'bright_indirect', 'low', 30, 'After blooming, cut off spent flowers and give it a 6-week dark period to rebloom.'),
  ('bromeliad', 'Bromeliad', 14, 'bright_indirect', 'high', 60, 'Keep the central cup filled with water. The plant blooms once then produces pups for the next generation.'),
  ('yucca', 'Yucca', 14, 'bright_direct', 'low', 60, 'Extremely drought tolerant. Sharp leaf tips — place away from high-traffic areas.'),
  ('cast_iron_plant', 'Cast Iron Plant', 14, 'low_to_medium', 'low', 90, 'Nearly indestructible — tolerates low light, drought, and temperature swings.'),
  ('christmas_cactus', 'Christmas Cactus', 10, 'bright_indirect', 'medium', 30, 'Trigger blooming by giving it 14 hours of darkness per night for 6 weeks before the holidays.'),
  ('ponytail_palm', 'Ponytail Palm', 21, 'bright_direct', 'low', 90, 'The bulbous trunk stores water — one of the most drought-tolerant houseplants. Rarely needs repotting.'),
  ('nerve_plant', 'Nerve Plant', 3, 'medium_indirect', 'high', 30, 'Needs consistently moist soil and very high humidity — ideal for terrariums.'),
  ('lucky_bamboo', 'Lucky Bamboo', 7, 'medium_indirect', 'medium', 30, 'Can grow in water or soil. Change water every 2 weeks if growing hydroponically.'),
  ('caladium', 'Caladium', 5, 'medium_indirect', 'high', 30, 'Goes dormant in winter — reduce watering and let it rest. Bold, heart-shaped leaves return each spring.')
ON CONFLICT (key) DO NOTHING;
